[package]
name = "libclgeom"
version = "0.1.0"
edition = "2022"
authors = ["Anders Lehn Reed <anders.lehn.reed@gmail.com>"]
license = "AGPL-3.0-or-later"
repository = "https://gitlab.com/anderslreed/libclgeom"

[lib]
crate-type = ["cdylib"]
test = true

[dependencies]
opencl3 = ">=0.6.3"
